config/routes.rb
require 'resque/server'
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  resources :comments
  
  get '/search' , to: "posts#search"
  get '/destroy/:id' , to: "posts#delete"
  get '/showPost/:id' , as: "showPost" , to: "posts#showPost"
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticate :user do
    mount Resque::Server.new, at: '/jobs'
  end

  get '/posts' => "posts#index", :as => :user_root
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
    after_create :sent_email
    
    def sent_email
        CommentMailer.comment_created(self).deliver_later
    end

    validates :comment, presence: true, length: { minimum: 1 }
    validates :post, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    belongs_to :user
    after_create :sent_email
    
    def sent_email
        PostMailer.post_created(self).deliver_later
    end
    
    validates :title, presence: true
    validates :content, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :addUser
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts
         has_many :comments

  def addUser
    dc = 'us5'
    unique_id = "e86db98f63"
    url = "https://#{dc}.api.mailchimp.com/3.0/lists/#{unique_id}/members"
    api_key = ENV['API_KEY']
      
          user_details = {
            email_address: self.email,
            status: "subscribed"
          }
          conn = Faraday.new(
            url: url,
            headers: {'Content-Type' => 'application/json', 'Authorization': "Bearer #{api_key}"}
          )
          response = conn.post() do |req|
            req.body = user_details.to_json
          end
      
          response_body = JSON.parse(response.body)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create 
        @comment = Comment.new(comment_params)
        @comment.post_id= params[:postId]
        @comment.comment = params[:comment] 
        @comment.email = params[:userName] 
        @comment.user_id = current_user.id
            respond_to do |format|
                if @comment.valid? and @comment.save
                    format.js
                end
            end
    end

    
    def destroy
        @comment = Comment.find(params[:id])
        authorize @comment
        respond_to do |format|
            if @comment.destroy
             format.js
            end
        end
    end

    def edit
        @comment = Comment.find(params[:id])
        respond_to do |format|
            format.js
        end
    end

    def show
        @comment = Comment.find(params[:id])
        respond_to do |format|
                format.js
            end
    end

    def update
        @comment = Comment.find(params[:id])
        authorize @comment
        @comment.update(comment: params[:comment])
        respond_to do |format|
            if @comment.valid? and @comment.save
                format.js
            end
        end
   end
    
    
    private
    def comment_params
      params.permit(:comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController;
    before_action :authenticate_user! 
    
    def index
        @post = Post.all.paginate(page: params[:page], per_page: 4)
        render "index"
    end
    
    def destroy
        @post = Post.find(params[:id])
        authorize @post
        @post.destroy
        flash[:alert] = "Post Deleted succesfully."
        redirect_to user_root_path
    end
    
    def edit
        @post = Post.find(params[:id])
        authorize @post
        @post.update(title: params[:title],content:params[:description])
        
        if @post.valid?
            @post.save
            flash[:alert] = "Post updated succesfully."
            redirect_to user_root_path
        else
            flash[:alert] = "Validation error."
            redirect_to post_path
        end    
    end

    def create 
        @post = Post.new(post_params)
        @post.title = params[:title]
        @post.content = params[:description]
        @post.user_id=current_user.id
        
        if @post.valid?
            @post.save
            flash[:alert] = "Post Created succesfully."
            redirect_to user_root_path
        else
            flash[:alert] = "Validation error."
            redirect_to user_root_path
        end
    end
    
    def show
        @post = Post.find(params[:id])
        @title =  @post.title
        @content =  @post.content
        @id = params[:id]
        authorize @post
        render "update"
    end
    
    def search
        @query = params[:query]
        @post = Post.where("posts.title LIKE ?",["%#{@query}%"]).paginate(page: params[:page], per_page: 4)
        render "index"
    end

    def delete
        @post = Post.find(params[:id])
        @title =  @post.title
        @content =  @post.content
        @id = params[:id]
        render "confirmationPostdelete"
    end
    
    def showPost
        @post = Post.find(params[:id])
        page = params[:page]
        @title =  @post.title
        @content =  @post.content
        @id = params[:id]
        @userName = @post.user.email
        @comment = Comment.where(post_id: params[:id]).all.order("created_at DESC").paginate(page: params[:page], per_page: 4)
        
        if @comment.length == 0 and page != nil
            page = Integer(page)
            page = (page - 1) > 1 ? (page - 1) : 1 
            redirect_to showPost_path(page:page) 
        else
            render "showPost"
    end
end
    
    private
    def post_params
      params.permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 70rem; margin-left:  200px;" id="card-<%= @comment.id %>">
    <h5 class="card-header">
        <%= @comment.email %>
    </h5>
    <div class="card-body">
        <p class="card-text">
            <%= @comment.comment %>
        </p>
        <% if current_user.email==@comment.email %>
            <a href="/comments/<%= @comment.id %>" data-method="DELETE" class="btn btn-danger" data-remote="true"
                id='deletePost'>Delete</a>
            <a href="/comments/<%= @comment.id %>/edit" data-method="GET" data-remote="true"
                class="btn btn-warning">Edit</a>
            <% elsif current_user.email==@comment.post.user.email %>
                <a href="/comments/<%= @comment.id %>" data-method="DELETE" class="btn btn-danger" data-remote="true"
                    id='deletePost'>Delete</a>
                <% end %>
    </div>
</div>

app/views/comments/_editComment.html.erb
<div class="card text-dark bg-light mb-3" style="max-width: 70rem; margin-left:  200px;" id="card-<%= @comment.id %>">
    <h5 class="card-header">
        <%= @comment.email %>
    </h5>
    <div class="card-body">
        <form method="PUT" action="/comments/<%= @comment.id %>" data-remote="true">
            <input name="comment" type="text" class="form-control" id="comment-<%= @comment.id %>"
                value="<%= @comment.comment %>">
            <br> </br>
            <a href="/comments/<%= @comment.id %>" data-method="DELETE" class="btn btn-danger" data-remote="true"
                id='deletePost'>Delete</a>
            <button type="Submit" class="btn btn-warning">Update</button>
            <a href="/comments/<%= @comment.id %>" data-method="GET" data-remote="true" class="btn btn-dark">Cancel</a>
        </form>
    </div>
</div>

app/views/comments/create.js.erb
$('#descriptionid').val('')
$( "#display" ).prepend("<%= j render 'comments/comment' %>");
location.reload(true);

app/views/comments/destroy.js.erb
$("#card-<%= @comment.id %>").remove();
location.reload(true);

  

app/views/comments/edit.js.erb
$("#card-<%= @comment.id %>").replaceWith("<%= j render 'comments/editComment' %>")

app/views/comments/show.js.erb
$("#card-<%= @comment.id %>").replaceWith("<%= j render 'comments/comment' %>")

app/views/comments/update.js.erb
$("#card-<%= @comment.id %>").replaceWith("<%= j render 'comments/comment' %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>
  <title>Post App</title>
  <%= stylesheet_link_tag 'application' , media: 'all' , 'data-turbolinks-track'=> true %> <%=
      javascript_include_tag 'application' , 'data-turbolinks-track'=> true %> <%= csrf_meta_tags %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous" />
</head>

<body class="bg-dark text-dark" style="width: 100%; height: 100vh">
  <% if notice %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <p>
        <%= notice %>
      </p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    <% end %>
      <% if alert %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <p>
            <%= alert %>
          </p>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <% end %>

          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>

          <%= yield %>
</body>

</html>

app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="#">Post App</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', user_root_path, method: :get, class: "nav-link
          text-white"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete,
          class: "nav-link text-white"%>
        </li>
      </ul>
      <form class="d-flex text-white" action="/search">
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
          name="query"
          method="GET"
        />
        <button class="btn btn-outline-success text-white" type="submit">
          Search
        </button>
      </form>
    </div>
  </div>
</nav>

app/views/posts/_paginate.html.erb
<div class="bg-dark" style="margin-left: 612px; max-width: 70rem;" id='pagination'>
    <%= will_paginate @comment, list_classes: %w(pagination bg-darkjustify-content-end) %>
</div>

app/views/posts/confirmationPostdelete.html.erb
<div class="text-center text-white bg-dark">
  <br> </br>
  <h1>Are you Sure you want to destroy the post below</h1>
  <br> </br>
  <h2>
    <%= @title %>
  </h2>
  <p class="lead">
    <%= @content %>
  </p>
  <br> </br>
  <a href="/posts/<%= @id  %>" data-method="DELETE" class="btn btn-danger">Delete</a>
  <%= link_to 'Back' , posts_path, method: :get, class: "btn btn-warning" %>
</div>

app/views/posts/index.html.erb
<%= render "header" %>
  <div class="p-3 mb-2 bg-dark text-dark padding-0">

    <div class=" text-center text-white bg-dark">
      <h2> Create a Post </b>
    </div>

    <form method="POST" action="/posts">
      <%= token_tag %>

        <div class="col-6" style="margin : 0 auto ">

          <div class="mb-3">
            <label for="titleid" class="form-label text-white bg-dark">Title</label>
            <input name="title" type="text" class="form-control " id="titleid">
          </div>

          <div class="mb-3">
            <label for="descriptionid" class="form-label text-white bg-dark">Description</label>
            <textarea name="description" class="form-control" id="descriptionid" rows="3"></textarea>
          </div>

          <div class="text-center">
            <button type="Submit" class="btn btn-primary">Create</button>
          </div>

        </div>
    </form>

    <br></br>

    <div class="text-center text-white bg-dark">
      <h2> Created Post </b>
        <br></br>
    </div>

    <div class="container mt-4">
      <div class="row">

        <% @post.each do |post| %>
          <div class="col-auto mb-3">
            <div class="card h-100 card-body" style="width: 18rem">
              <div class="card-body ">
                <h5 class="card-title">
                  <%= post.title %>
                </h5>
                <p class="card-text text-truncate">
                  <%= post.content %>. <br></br> By - <%= post.user.email %>
                </p>
                <% if user_signed_in? %>
                  <% if post.user_id==current_user.id %>
                    <a href="/showPost/<%= post.id %>" data-method="GET" class="btn btn-dark">Show Post</a>
                    <br> </br>
                    <a href="/destroy/<%= post.id %>" data-method="GET" class="btn btn-danger">Delete</a>
                    <a href="/posts/<%= post.id %>" data-method="GET" class="btn btn-warning">Update</a>
                    <% else %>
                      <a href="/showPost/<%= post.id %>" data-method="GET" class="btn btn-dark">Show Post</a>
                      <br> </br>
                      <p class="card-text"> Member of Post App</p>
                      <% end %>
                        <% end %>

              </div>
            </div>
          </div>


          <% end %>
      </div>
    </div>
    <div class="bg-dark" style="margin-left: 130px; margin-right: 250px; width: 50%">
      <%= will_paginate @post, list_classes: %w(pagination bg-dark justify-content-end ) ,previous_label: "Previous" ,
        next_label: "Next" %>
    </div>

  </div>

app/views/posts/showPost.html.erb
<div id=test class="text-center text-white bg-dark">
    <br> </br>
    <h1>Welcome to the Post</h1>
    <br> </br>
    <h2>
        <%= @title %>
    </h2>
    <p class="lead">
        <%= @content %>
    </p>
    <br> </br>

    <form id="AddComment" name="AddComment" method="POST" action="/comments" data-remote="true">
        <%= token_tag %>
            <input type="hidden" name="postId" value="<%= @id  %>">
            <input type="hidden" name="userName" value="<%= current_user.email %>">
            <input type="hidden" name="postTitle" value=" <%= @title %>">
            <input type="hidden" name="postContent" value="<%= @content %>">

            <div class="col-6" style="margin : 0 auto ">

                <div class="mb-3">
                    <textarea name="comment" class="form-control" id="descriptionid"
                        placeholder="Add a comment to a post" rows="3"></textarea>
                </div>

                <div class="text-center">
                    <button type="Submit" id='create' class="btn btn-primary" data-remote="true">Add Comment</button>
                    <%= link_to 'Back' , posts_path, method: :get, class: "btn btn-light" %>
                </div>

            </div>
    </form>

</div>
<br> </br>
<div id='display'>
    <% @comment.each do |comment| %>
        <div class="card text-dark bg-light mb-3" style="max-width: 70rem; margin-left:  200px;"
            id="card-<%= comment.id %>">
            <h5 class="card-header">
                <%= comment.email %>
            </h5>
            <div class="card-body">
                <p class="card-text">
                    <%= comment.comment %>
                </p>
                <% if current_user.email==comment.email %>
                    <a href="/comments/<%= comment.id %>" data-method="DELETE" class="btn btn-danger" data-remote="true"
                        id='deletePost'>Delete</a>
                    <a href="/comments/<%= comment.id %>/edit" data-method="GET" data-remote="true"
                        class="btn btn-warning">Edit</a>
                    <% elsif current_user.email==comment.post.user.email %>
                        <a href="/comments/<%= comment.id %>" data-method="DELETE" class="btn btn-danger"
                            data-remote="true" id='deletePost'>Delete</a>
                        <% end %>



            </div>
        </div>

        <% end %>
            <div class="bg-dark" style="margin-left: 612px; max-width: 70rem;">
                <%= will_paginate @comment, list_classes: %w(pagination bg-darkjustify-content-end),
                    previous_label: "Previous" , next_label: "Next" %>
            </div>

</div>

app/views/posts/update.html.erb
<div class="p-3 mb-2 bg-dark text-dark padding-0">

  <div class="text-center text-white bg-dark">
    <h2> Update a Post <h2>
  </div>

  <form method="GET" action="/posts/<%= @id %>/edit">
    <input type="hidden" value="<%= @id  %>">
    <%= token_tag %>
      <div class="col-6" style="margin : 0 auto ">

        <div class="mb-3">
          <label for="titleid" class="form-label text-white bg-dark">Title</label>
          <input name="title" type="text" class="form-control " id="titleid" value="<%= @title %>">
        </div>

        <div class="mb-3">
          <label for="descriptionid" class="form-label text-white bg-dark">Description</label>
          <textarea name="description" class="form-control" id="descriptionid" rows="3"><%= @content %>  </textarea>
        </div>

        <button type="Submit" class="btn btn-danger">Update</button>
        <%= link_to 'Back' , posts_path, method: :get, class: "btn btn-warning" %>

      </div>
  </form>
</div>